// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlPrieto.Data;

#nullable disable

namespace UrlPrieto.Migrations
{
    [DbContext(typeof(UrlContext))]
    [Migration("20231031233920_UrlMigration")]
    partial class UrlMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("UrlPrieto.Entities.Url", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("largeUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("smallUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Url");
                });
#pragma warning restore 612, 618
        }
    }
}
